### ISSUE TITLE
In place result of the command

### ISSUE THREAD

**Issue by np** [snipem/vscode-run-script#2]
Sometimes I'd like to directly insert the result of a command in below the `# run: command`.
Do you think your extension could have this feature?

**Comment by snipem** [comment]
No, I have no plans on adding this feature. The console window is the main output. Adding the result to the file would add additional layers of complexity like escaping the results or handling multi line results. 

But you can easily do this this on your own. Try something like:

```bash
#!/bin/bash
# run: result=$(./insert-test.sh) && gsed -i "3i # result: $result" insert-test.sh

echo "hello world!"
```

which will add the result to the file, VS Code loads the file automatically:

![2020-05-08 19 37 30](https://user-images.githubusercontent.com/985581/81432739-bf919380-9163-11ea-8db2-86cab6177191.gif)

`gsed` is GNU sed on my Mac.
